apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: dashboard
spec:
  interval: "${infrastructure_vso_release_interval}"
  chart:
    spec:
      chart: weave-gitops
      version: "4.0.36"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: dashboard
      interval: 12h
  values:
    extraLabels:
      it.example.com/owned-by: sre-team
