apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: weave-gitops
  namespace: dashboard
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/weaveworks/charts/weave-gitops
