apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rbac-manager
  namespace: rbac-manager
spec:
  interval: "${infrastructure_rbac_manager_release_interval}"
  chart:
    spec:
      chart: rbac-manager
      version: "1.21.0"
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
        namespace: rbac-manager
      interval: 12h
  values:
    image:
      pullPolicy: "IfNotPresent"
