apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vault-secrets-operator/base.yaml
  - nginx/base.yaml
  - external-secrets-operator/base.yaml
  - rbac-manager/base.yaml

patches:
- patch: |-
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: not-used
    spec:
      postBuild:
        substitute:
          meta_cluster_name: "${meta_cluster_name}"
          meta_network_zone: "${meta_network_zone}"
          infrastructure_nginx_release_interval: "${infrastructure_nginx_release_interval:=30m}"
          infrastructure_vso_release_interval: "${infrastructure_vso_release_interval:=30m}"
          infrastructure_eso_release_interval: "${infrastructure_eso_release_interval:=30m}"
          infrastructure_rbac_manager_release_interval: "${infrastructure_rbac_manager_release_interval:=30m}"
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
